export const MockExamTopics = [
    'Algebra',
    'Geometry',
    'Trigonometry',
    'Calculus',
    'Physics',
    'Chemistry',
    'Biology',
    'Computer Science',
    'History',
    'Geography',
    'Political Science',
    'Economics',
    'Statistics',
    'Philosophy',
    'Psychology',
  ];

export const MockAutoQuestions = [
    { topic: "Algebra", easy: 5, medium: 7, hard: 2 },
    { topic: "Biology", easy: 6, medium: 4, hard: 5 },
    { topic: "Calculus", easy: 4, medium: 6, hard: 3 },
    { topic: "Data Structures", easy: 7, medium: 5, hard: 4 },
    { topic: "Electronics", easy: 8, medium: 6, hard: 3 },
    { topic: "Functions", easy: 5, medium: 5, hard: 2 },
    { topic: "Geometry", easy: 9, medium: 4, hard: 3 },
    { topic: "History", easy: 10, medium: 6, hard: 2 },
    { topic: "Integration", easy: 6, medium: 7, hard: 5 },
    { topic: "Java Programming", easy: 7, medium: 5, hard: 3 },
    { topic: "Kinematics", easy: 5, medium: 8, hard: 4 },
    { topic: "Linear Algebra", easy: 4, medium: 6, hard: 5 },
    { topic: "Macroeconomics", easy: 8, medium: 7, hard: 3 },
    { topic: "Networks", easy: 6, medium: 5, hard: 2 },
    { topic: "Optimization", easy: 4, medium: 8, hard: 5 },
    { topic: "Physics", easy: 5, medium: 7, hard: 4 },
    { topic: "Quantum Mechanics", easy: 3, medium: 6, hard: 5 },
    { topic: "Robotics", easy: 7, medium: 4, hard: 6 },
    { topic: "Statistics", easy: 6, medium: 5, hard: 3 },
    { topic: "Trigonometry", easy: 8, medium: 7, hard: 4 },
    { topic: "UML Diagrams", easy: 5, medium: 6, hard: 3 },
    { topic: "Vectors", easy: 7, medium: 5, hard: 2 },
    { topic: "Web Development", easy: 9, medium: 4, hard: 3 },
    { topic: "XML Parsing", easy: 6, medium: 5, hard: 4 },
    { topic: "Yield Curve Analysis", easy: 5, medium: 8, hard: 2 },
    { topic: "Zoology", easy: 7, medium: 4, hard: 5 },
  ];
  